remove requirement for ndep from aquaplanet cases
EarthWorksOrg/CAM pull request #6
Opened 2023-10-27 14:19 UTC by jedwards4b

Removes the requirement for an ndep_srf file for aquaplanet cases.

2023-11-06 18:46 UTC, gdicker1 requested changes
I may need guidance on how to use this, but I couldn't get a QPC6 case to run with this change.

I cloned the develop branch of EarthWorks, checked out externals, then merged this into `components/cam` and created a QPC6 case as I normally do:
```
./cime/scripts/create_newcase --compset QPC6 --res mpasa120_mpasa120 --project UCSU0085 --driver nuopc --case QPC6.mpasa120.CAMPR6 --run-unsupported --input-dir /glade/p/univ/ucsu0085/inputdata2/
```

Once setup, built, and submitted (with no extra steps) this case fails in initialization from within [cam/src/chemistry/mozart/mo_drydep.F90 line 382](https://github.com/EarthWorksOrg/CAM/blob/884ae44068d9afa8fec05f6101985f5aa633ac6b/src/chemistry/mozart/mo_drydep.F90#L382) since the `mapping` array isn't allocated.

Could you shed any light on whether my setup is wrong or how to fix this error? @jedwards4b

2023-11-06 18:46 UTC, gdicker1 commented on bld/namelist_files/namelist_defaults_cam.xml
> +<mpas_len_disp hgrid="mpasa3p75"> 3750.0D0</mpas_len_disp>
Smaller ask: @jedwards4b could you extend this change for the `mpas_dt` section a few lines above?

2023-11-06 19:04 UTC, jedwards4b commented
I thought that I had tested this change adequately last week, but I ran into the same problem you are finding when I tried this morning.  Sorry, I'll repackage the non ndep related changes this afternoon so that you can get those at least.

2024-05-30 20:25 UTC, gdicker1 commented
Since there has been no movement on this in a while, I'll close for now. We may have even gotten the changes through another update!

Feel free to open and refresh this if it still applies!

2024-05-30 20:25 UTC, closed without merging